- hosts: all
  user: vagrant
  become: yes
  become_method: sudo
  vars:
    node_version: 6.9.4

  tasks:
    - include: tasks/initSystem.yml
    - include: tasks/nodejs.yml
    - include: tasks/docker.yml
    - include: tasks/mongodb.yml
    - include: tasks/redis.yml
    - include: tasks/tools.yml
